# Generated by Django 2.0.3 on 2020-05-14 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='size',
            name='size',
            field=models.CharField(blank=True, choices=[('Small', 'Small'), ('Large', 'Large')], default='Small', max_length=8),
        ),
    ]
