# Generated by Django 2.0.3 on 2020-05-15 14:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0003_auto_20200514_1435'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, choices=[('Pizza', 'pizza'), ('Subs', 'subs'), ('Pasta', 'pasta'), ('Salads', 'salads'), ('Dinner Platters', 'platters')], default='Pizza', max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Crust',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crust', models.CharField(choices=[('REG', 'regular'), ('SIL', 'sicilian')], default='REG', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('toppings_count', models.IntegerField()),
                ('price', models.FloatField(default=0.5)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_category', to='orders.Category')),
                ('crust', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_crust', to='orders.Crust')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_size', to='orders.Size')),
                ('toppings', models.ManyToManyField(blank=True, related_name='item_toppings', to='orders.Topping')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordered', models.BooleanField(default=False)),
                ('ordered_date', models.DateTimeField(auto_now_add=True)),
                ('shipped_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('PREP', 'preparing'), ('READ', 'ready'), ('SHIP', 'shipped')], default='PREP', max_length=4)),
                ('shipping', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item', to='orders.MenuItem')),
            ],
        ),
        migrations.RemoveField(
            model_name='pizza',
            name='size_option',
        ),
        migrations.RemoveField(
            model_name='pizza',
            name='toppings_option',
        ),
        migrations.DeleteModel(
            name='Pizza',
        ),
        migrations.AddField(
            model_name='order',
            name='item_order',
            field=models.ManyToManyField(to='orders.OrderItem'),
        ),
        migrations.AddField(
            model_name='order',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
    ]
