# Generated by Django 2.0.3 on 2020-05-16 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20200515_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
