# Generated by Django 2.0.3 on 2020-05-16 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20200516_0923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crust',
            name='crust',
            field=models.CharField(choices=[('Regular', 'regular'), ('Sicilian', 'sicilian')], default='Regular', max_length=8),
        ),
    ]
