# Generated by Django 2.0.3 on 2020-05-16 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_auto_20200516_0924'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='quantity',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
