# Generated by Django 2.0.3 on 2020-05-17 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_auto_20200516_1402'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='toppings',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='toppings',
            field=models.ManyToManyField(blank=True, related_name='item_toppings', to='orders.Topping'),
        ),
    ]
