# Generated by Django 2.0.3 on 2020-05-17 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_auto_20200517_1000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.CharField(choices=[('Pizza', 'pizza'), ('Subs', 'subs'), ('Pasta', 'pasta'), ('Salads', 'salads'), ('Dinner Platters', 'platters')], default='Pizza', max_length=64),
        ),
        migrations.AlterField(
            model_name='crust',
            name='crust',
            field=models.CharField(blank=True, choices=[('Regular', 'regular'), ('Sicilian', 'sicilian')], default='Regular', max_length=8),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='crust',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='item_crust', to='orders.Crust'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='size',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='item_size', to='orders.Size'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='toppings_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipped_date',
            field=models.DateTimeField(blank=True),
        ),
    ]
