# Generated by Django 2.0.3 on 2020-05-19 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_auto_20200518_1420'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToppingAmount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4')], default=0)),
            ],
        ),
        migrations.RenameField(
            model_name='menuitem',
            old_name='title',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='toppings_count',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='item',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='toppings',
        ),
        migrations.AddField(
            model_name='menuitem',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.MenuItem'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Category'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='crust',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='orders.Crust'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Size'),
        ),
        migrations.AlterField(
            model_name='size',
            name='size',
            field=models.CharField(choices=[('Small', 'Small'), ('Large', 'Large')], default='Small', max_length=8),
        ),
        migrations.AddField(
            model_name='toppingamount',
            name='pizza',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='topping_amounts', to='orders.MenuItem'),
        ),
        migrations.AddField(
            model_name='toppingamount',
            name='topping',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='topping_amounts', to='orders.Topping'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='toppings',
            field=models.ManyToManyField(blank=True, related_name='food_with_toppings', through='orders.ToppingAmount', to='orders.Topping'),
        ),
    ]
