# Generated by Django 2.0.3 on 2020-05-19 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_auto_20200519_1151'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='toppingamount',
            name='pizza',
        ),
        migrations.RemoveField(
            model_name='toppingamount',
            name='topping',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='toppings',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='amount',
            field=models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4')], default=0),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='topping',
            field=models.ManyToManyField(blank=True, related_name='pizzas', to='orders.Topping'),
        ),
        migrations.RemoveField(
            model_name='order',
            name='item_order',
        ),
        migrations.AddField(
            model_name='order',
            name='item_order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.OrderItem'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.MenuItem'),
        ),
        migrations.DeleteModel(
            name='ToppingAmount',
        ),
    ]
