# Generated by Django 2.0.3 on 2020-05-19 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_auto_20200519_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='item_order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.OrderItem'),
        ),
    ]
