# Generated by Django 2.0.3 on 2020-05-21 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0018_auto_20200520_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='crust',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.Crust'),
        ),
    ]
